package view;

import controller.ControllerComponentes;
import controller.ControllerHistoricoComponente;
import controller.ControllerLogin;
import controller.ControllerProcessos;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Matheus Mattos e Raylane Fernandes
 */
public class TelaLogin extends javax.swing.JFrame {
    ControllerHistoricoComponente controllerHistoricoComponente = new ControllerHistoricoComponente();
    ControllerProcessos controllerProcessos = new ControllerProcessos();
    ControllerComponentes controllerComponentes = new ControllerComponentes();

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        //Colocando cor no fundo da página;
        getContentPane().setBackground(Color.decode("#080425"));

        // Variaveis para adicionar "favicon" na barra superior da página;
        URL caminhoImagem = this.getClass().getClassLoader().getResource("tela-login-rxmonitoramento.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoImagem);
        setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelLogo = new javax.swing.JLabel();
        jButtonAcessar = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        pwdLogin = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLogo1 = new javax.swing.JLabel();

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela-login-rxmonitoramento.png"))); // NOI18N
        jLabelLogo.setRequestFocusEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(8, 4, 37));
        getContentPane().setLayout(null);

        jButtonAcessar.setBackground(new java.awt.Color(79, 80, 101));
        jButtonAcessar.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 12)); // NOI18N
        jButtonAcessar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAcessar.setText("ENTRAR");
        jButtonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcessar);
        jButtonAcessar.setBounds(160, 400, 120, 30);

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(120, 260, 200, 40);

        pwdLogin.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pwdLogin);
        pwdLogin.setBounds(120, 330, 200, 40);

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("senha");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 310, 200, 17);

        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("e-mail ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 240, 200, 17);

        jLabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela-login-rxmonitoramento.png"))); // NOI18N
        jLabelLogo1.setRequestFocusEnabled(false);
        getContentPane().add(jLabelLogo1);
        jLabelLogo1.setBounds(20, 0, 450, 480);

        setSize(new java.awt.Dimension(447, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarActionPerformed
        String Email = this.txtEmail.getText();
        String Senha = new String(this.pwdLogin.getPassword());

        ControllerLogin validation = new ControllerLogin();
        TelaInit telaInit = new TelaInit();

        if (validation.validationDataLogin(Email, Senha)) {
            System.out.println("Bem vindo ao RX-Monitoramento");
            System.out.println("Usuario Verificado");
            try {
                controllerHistoricoComponente.insertHistoricoComponentes();
                controllerProcessos.insertProcessos();
                controllerComponentes.insertComponentes();
                telaInit.setVisible(true);
                dispose();

            } catch (UnknownHostException ex) {
                Logger.getLogger(view.TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            

        } else {
            JOptionPane.showMessageDialog(rootPane, "Email/Senha inválido");

        }
    }//GEN-LAST:event_jButtonAcessarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAcessar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JPasswordField pwdLogin;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
