/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import services.ServiceCpu;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author raylane
 */
public class TelaCpu extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaCpu() {
        initComponents();
        ServiceCpu serviceCpu = new ServiceCpu();

        lblNomeProcessador.setText(serviceCpu.getNomeProcessador());
        lblCpuLogicas.setText(serviceCpu.cpuLogicas() + "");
        lblCpuFisicas.setText(serviceCpu.cpuFisicas() + "");

        Timer timer = new Timer();
        Integer delay = 3000;
        Integer interval = 1000;

        timer.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                String emUso = String.format("%.2f %%", serviceCpu.emUso());
                lblEmUso.setText(emUso);
            }
        }, delay, interval);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblCPU = new javax.swing.JLabel();
        lblNomeProc = new javax.swing.JLabel();
        lblNomeProcessador = new javax.swing.JLabel();
        lblCpuF = new javax.swing.JLabel();
        lblCpuFisicas = new javax.swing.JLabel();
        lblUso = new javax.swing.JLabel();
        lblEmUso = new javax.swing.JLabel();
        lblCpuL = new javax.swing.JLabel();
        lblCpuLogicas = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-rx-monitoramento.png"))); // NOI18N

        lblCPU.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblCPU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCPU.setText("CPU");

        lblNomeProc.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblNomeProc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeProc.setText("Nome processador:");

        lblNomeProcessador.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        lblNomeProcessador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeProcessador.setText("...");

        lblCpuF.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblCpuF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpuF.setText("CPUS Físicas:");

        lblCpuFisicas.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        lblCpuFisicas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpuFisicas.setText("...");

        lblUso.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblUso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUso.setText("Em uso:");

        lblEmUso.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        lblEmUso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmUso.setText("...");

        lblCpuL.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblCpuL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpuL.setText("CPUS Lógicas:");

        lblCpuLogicas.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        lblCpuLogicas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpuLogicas.setText("...");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLogo)
                        .addGap(254, 254, 254))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCpuL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCpuLogicas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCpuF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCpuFisicas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmUso, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeProc, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblCPU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNomeProcessador, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblLogo)
                .addGap(36, 36, 36)
                .addComponent(lblCPU)
                .addGap(35, 35, 35)
                .addComponent(lblNomeProc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeProcessador)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmUso))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCpuF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCpuFisicas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCpuL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCpuLogicas)))
                .addGap(29, 29, 29)
                .addComponent(btnVoltar)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(627, 491));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaInicial telaInicial = new TelaInicial();
        telaInicial.setLocationRelativeTo(null);
        telaInicial.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCpu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCpu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCpu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCpu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCpu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblCPU;
    private javax.swing.JLabel lblCpuF;
    private javax.swing.JLabel lblCpuFisicas;
    private javax.swing.JLabel lblCpuL;
    private javax.swing.JLabel lblCpuLogicas;
    private javax.swing.JLabel lblEmUso;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNomeProc;
    private javax.swing.JLabel lblNomeProcessador;
    private javax.swing.JLabel lblUso;
    // End of variables declaration//GEN-END:variables
}
